---
version: '3'

services:

  base: &base
    image: pr8kerl/gobuilder:1.10
    volumes:
      - .:/go/src/github.com/pr8kerl/slackers
    working_dir: /go/src/github.com/pr8kerl/slackers

  slackers:
    build: .
    volumes:
      - ./config.ini:/config.ini
    entrypoint: /slackers 
    environment:
      - SLACK_API_TOKEN
      - LDAP_PASSWD

  make:
    <<: *base
    entrypoint: make 
