base:
  build: .
  volumes:
    - .:/go/src/github.com/pr8kerl/lusers
  working_dir: /go/src/github.com/pr8kerl/lusers

glide:
  extends:
    service: base
  entrypoint: glide

console:
  extends:
    service: base
  entrypoint: bash

make:
  extends:
    service: base
  entrypoint: make 

