---
version: '3'

services:
  base: &base
    build: .
    volumes:
      - .:/go/src/github.com/pr8kerl/slackers
    working_dir: /go/src/github.com/pr8kerl/slackers
    entrypoint: make 

  make:
    <<: *base
    environment:
      - GITHUB_TOKEN
      - TRAVIS_TAG

  dep:
    <<: *base
    entrypoint: dep 
